*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:00:25 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address myapp.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9e60848
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x9e60848 pid: 2866 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2866)
spawned uWSGI worker 1 (pid: 2867, cores: 1)
spawned uWSGI worker 2 (pid: 2868, cores: 1)
spawned uWSGI worker 3 (pid: 2869, cores: 1)
spawned uWSGI worker 4 (pid: 2870, cores: 1)
spawned uWSGI worker 5 (pid: 2871, cores: 1)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket myapp.sock removed.
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:23:22 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address myapp.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x99e0848
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "./wsgi.py", line 11, in <module>
    logging.config.fileConfig(config.log_ini)
  File "/usr/lib/python3.4/logging/config.py", line 76, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python3.4/logging/config.py", line 109, in _create_formatters
    flist = cp["formatters"]["keys"]
  File "/usr/lib/python3.4/configparser.py", line 937, in __getitem__
    raise KeyError(key)
KeyError: 'formatters'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3147)
spawned uWSGI worker 1 (pid: 3151, cores: 1)
spawned uWSGI worker 2 (pid: 3152, cores: 1)
spawned uWSGI worker 3 (pid: 3153, cores: 1)
spawned uWSGI worker 4 (pid: 3154, cores: 1)
spawned uWSGI worker 5 (pid: 3155, cores: 1)
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:26:12 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address myapp.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xa016848
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xa016848 pid: 3188 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3188)
spawned uWSGI worker 1 (pid: 3192, cores: 1)
spawned uWSGI worker 2 (pid: 3193, cores: 1)
spawned uWSGI worker 3 (pid: 3194, cores: 1)
spawned uWSGI worker 4 (pid: 3195, cores: 1)
spawned uWSGI worker 5 (pid: 3196, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket myapp.sock changed inode. Skip removal
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:29:07 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address myapp.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x859a848
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x859a848 pid: 3299 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3299)
spawned uWSGI worker 1 (pid: 3303, cores: 1)
spawned uWSGI worker 2 (pid: 3304, cores: 1)
spawned uWSGI worker 3 (pid: 3305, cores: 1)
spawned uWSGI worker 4 (pid: 3306, cores: 1)
spawned uWSGI worker 5 (pid: 3307, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket myapp.sock changed inode. Skip removal
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:37:07 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address vnailmbot.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8bff850
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x8bff850 pid: 3413 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3413)
spawned uWSGI worker 1 (pid: 3417, cores: 1)
spawned uWSGI worker 2 (pid: 3418, cores: 1)
spawned uWSGI worker 3 (pid: 3419, cores: 1)
spawned uWSGI worker 4 (pid: 3420, cores: 1)
spawned uWSGI worker 5 (pid: 3421, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket myapp.sock removed.
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3420|app: 0|req: 1/1] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:20 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3421|app: 0|req: 1/2] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:21 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3419|app: 0|req: 1/3] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:23 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3420|app: 0|req: 2/4] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:24 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3418|app: 0|req: 1/5] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:27 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3419|app: 0|req: 2/6] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:33 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3421|app: 0|req: 2/7] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:35 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3420|app: 0|req: 3/8] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:45 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3419|app: 0|req: 3/9] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:51 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 25, in application
      File "./wsgi.py", line 33, in chek_user_settings
    c = conn.cursor()
NameError: name 'conn' is not defined
[pid: 3417|app: 0|req: 1/10] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:37:54 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:38:01 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address vnailmbot.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8848850
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket vnailmbot.sock changed inode. Skip removal
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x8848850 pid: 3443 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3443)
spawned uWSGI worker 1 (pid: 3447, cores: 1)
spawned uWSGI worker 2 (pid: 3448, cores: 1)
spawned uWSGI worker 3 (pid: 3449, cores: 1)
spawned uWSGI worker 4 (pid: 3450, cores: 1)
spawned uWSGI worker 5 (pid: 3451, cores: 1)
[pid: 3450|app: 0|req: 1/1] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:07 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 242 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3447|app: 0|req: 1/2] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:15 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 288 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 3448|app: 0|req: 1/3] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:20 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 283 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 3449|app: 0|req: 1/4] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:23 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 250 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3447|app: 0|req: 2/5] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:24 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 74 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3450|app: 0|req: 2/6] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:33 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 71 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3451|app: 0|req: 1/7] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:45 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 371 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3447|app: 0|req: 3/8] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:38:54 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 74 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3450|app: 0|req: 3/9] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:39:04 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 102 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3448|app: 0|req: 2/10] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:39:24 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 87 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3449|app: 0|req: 2/11] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:39:33 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 70 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3448|app: 0|req: 3/12] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:39:50 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 68 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3447|app: 0|req: 4/13] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:39:54 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 72 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3449|app: 0|req: 3/14] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:41:19 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 72 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3447|app: 0|req: 5/15] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:13 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3450|app: 0|req: 4/16] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:15 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3447|app: 0|req: 6/17] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:20 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3450|app: 0|req: 5/18] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:28 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:53:29 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address vnailmbot.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8247850
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x8247850 pid: 3490 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3490)
spawned uWSGI worker 1 (pid: 3494, cores: 1)
spawned uWSGI worker 2 (pid: 3495, cores: 1)
spawned uWSGI worker 3 (pid: 3496, cores: 1)
spawned uWSGI worker 4 (pid: 3497, cores: 1)
spawned uWSGI worker 5 (pid: 3498, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket vnailmbot.sock changed inode. Skip removal
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3497|app: 0|req: 1/1] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:37 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3498|app: 0|req: 1/2] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:39 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3496|app: 0|req: 1/3] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:43 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3495|app: 0|req: 1/4] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:44 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 2 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select lang from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3497|app: 0|req: 2/5] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:53:51 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select id from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3498|app: 0|req: 2/6] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:54:08 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 26, in application
      File "./wsgi.py", line 35, in chek_user_settings
    c.execute ("""select id from users where id='%s'""" % user_id)
sqlite3.OperationalError: no such column: lang
[pid: 3497|app: 0|req: 3/7] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:54:16 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:54:16 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address vnailmbot.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x8daf850
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x8daf850 pid: 3527 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3527)
spawned uWSGI worker 1 (pid: 3531, cores: 1)
spawned uWSGI worker 2 (pid: 3532, cores: 1)
spawned uWSGI worker 3 (pid: 3533, cores: 1)
spawned uWSGI worker 4 (pid: 3534, cores: 1)
spawned uWSGI worker 5 (pid: 3535, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket vnailmbot.sock changed inode. Skip removal
[pid: 3534|app: 0|req: 1/1] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:54:31 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 282 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
[pid: 3531|app: 0|req: 1/2] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:54:40 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 250 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
[pid: 3532|app: 0|req: 1/3] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:55:16 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 239 msecs (HTTP/1.1 200) 1 headers in 44 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
*** Starting uWSGI 2.0.15 (32bit) on [Fri May 12 11:59:34 2017] ***
compiled with version: 4.8.4 on 27 April 2017 21:17:18
os: Linux-2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015
nodename: ickd
machine: i686
clock source: unix
detected number of CPU cores: 1
current working directory: /opt/vnailmbot
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /opt/vnailmbot/bin/
your processes number limit is 513873
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address vnailmbot.sock fd 3
Python version: 3.4.3 (default, Nov 17 2016, 01:16:04)  [GCC 4.8.4]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x914c850
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 383928 bytes (374 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x914c850 pid: 3558 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3558)
spawned uWSGI worker 1 (pid: 3562, cores: 1)
spawned uWSGI worker 2 (pid: 3563, cores: 1)
spawned uWSGI worker 3 (pid: 3564, cores: 1)
spawned uWSGI worker 4 (pid: 3565, cores: 1)
spawned uWSGI worker 5 (pid: 3566, cores: 1)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM WARNING: unix socket vnailmbot.sock changed inode. Skip removal
[pid: 3564|app: 0|req: 1/1] 149.154.167.209 () {36 vars in 526 bytes} [Fri May 12 11:59:56 2017] POST /385249163:AAHQNYWHvNZu_RkhkeJ6nk-2fVmGPrSxfpU => generated 0 bytes in 285 msecs (HTTP/1.1 200) 1 headers in 44 bytes (1 switches on core 0)
